### ISSUE TITLE
I am a beginner user and I couldn't run it

### ISSUE THREAD

**Issue by rrrcabral** [freemocap/skelly_synchronize#40]
I'm not familiar with Python and I couldn't figure out the right working commands or locations to run.
Wouldn't it be possible to make a GUI that's easy to open by just clicking on a portable .exe?

**Comment by philipqueen** [comment]
Hi, sorry you're having issues running the GUI. 

It's possible to create a portable .exe, but in our experience testing this they're hard to get right. In particular, we had problems with the GUI running very slowly through the exe. Running as an exe is not the primary mode of execution for python (it is an interpreted, not compiled language). I can look into testing an exe again, but it will probably be fairly low on my priority list. 

In the mean time, I highly recommend looking through [this python setup guide](https://realpython.com/python-first-steps/), particularly the sections [How to Download and Install Python](https://realpython.com/python-first-steps/#how-to-download-and-install-python) and [The Python Package Index and pip](https://realpython.com/python-first-steps/#the-python-package-index-and-pip). Figuring out how to run python on your machine is a hurdle, but there's a lot of help online.
